<a href="https://colab.research.google.com/github/lgeralas/Hola-mundo/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Extracción de datos**

Filtros de datos: filtros que nos ayudan a buscar algun conjunto o datos en concreto, ya sean categóricos o númericos

In [19]:
#Importamos librerias requeridas
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files 
files.upload()

In [42]:
#Convertir de dataframe 
df= pd.read_csv('file.csv')
df

,Periodo,Trimestre,Entidad_Federativa,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
0,2005,1,Nacional,Hombres,4384907,26597801,16.485975660000000000000
1,2005,1,Nacional,Mujeres,2690296,14843275,18.124679360000000000000
2,2005,1,Aguascalientes,Hombres,56407,246177,22.913188480000000000000
3,2005,1,Aguascalientes,Mujeres,28430,145656,19.518591750000000000000
4,2005,1,Baja California,Hombres,167651,768989,21.801482210000000000000
...,...,...,...,...,...,...,...
4549,2022,1,Veracruz,Mujeres,107640,1190733,9.0398099320000000000000
4550,2022,1,Yucat n,Hombres,101992,691397,14.751582670000000000000
4551,2022,1,Yucat n,Mujeres,82759,478943,17.279509250000000000000
4552,2022,1,Zacatecas,Hombres,44105,402326,10.962503040000000000000
4553,2022,1,Zacatecas,Mujeres,39472,255761,15.43315830000000000000

**Filtros básicos para variables cualitativas**

In [ ]:
#Filtro por objeto 
filtro1=df[df['Entidad_Federativa']== 'Yucat n']
filtro1

In [ ]:
#Filtro por filas
#filtro2= df.iloc[300:302,: ] # filas consecutivas
filtro2=df.iloc[[1000,2000,3000],:] # filas no consecutivas[filas, columnas]
filtro2

In [ ]:
#filtro por columnas
#filtro3=df.iloc[:,4:7] #columnas consecutivas
filtro3=df.iloc[:,[1,3,5]]   #columnas no consecutivas
filtro3

In [ ]:
#combinación de filtros [filas,columnas]
filtromix=df.iloc[[1000,2,300],[0,4]]
filtromix

In [50]:
#filtro filas vs columnas
#paso : leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()
df=pd.read_csv(io.BytesIO(uploaded['file.csv']),index_col=2) #solo las categoricas pueden separarse por índice

Saving file.csv to file (9).csv

In [ ]:
#Paso 2: Aplicamos Filtro de filas vs columnas
filtro4=df.loc[["Puebla","Durango"],["Poblacion_ocupada_en_la_industria_manufacturera"]]
filtro4

In [ ]:
#filtro cabecera 
filtro5=df.head()
filtro5

**Filtros básicos para variables cuantitativas**

In [56]:
#filtro por comparación
filtro6=df[df['Periodo']>2012]
filtro6

,Periodo,Trimestre,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
Entidad_Federativa,,,,,,
Nacional,2013,1,Hombres,4803715,30071937,15.974079090000000000000
Nacional,2013,1,Mujeres,2692519,18286318,14.724227150000000000000
Aguascalientes,2013,1,Hombres,71720,298434,24.03211430000000000000
Aguascalientes,2013,1,Mujeres,31934,186235,17.147152790000000000000
Baja California,2013,1,Hombres,157741,874914,18.029314880000000000000
...,...,...,...,...,...,...
Veracruz,2022,1,Mujeres,107640,1190733,9.0398099320000000000000
Yucat n,2022,1,Hombres,101992,691397,14.751582670000000000000
Yucat n,2022,1,Mujeres,82759,478943,17.279509250000000000000
Zacatecas,2022,1,Hombres,44105,402326,10.962503040000000000000
Zacatecas,2022,1,Mujeres,39472,255761,15.43315830000000000000

**Filtros básicos con conectores lógicos**

In [57]:
#filtro Y
filtro7=df[(df['Periodo']>2006)&(df['Sexo']=='Mujeres')]
filtro7

,Periodo,Trimestre,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
Entidad_Federativa,,,,,,
Nacional,2007,1,Mujeres,2798066,16239553,17.229944690000000000000
Aguascalientes,2007,1,Mujeres,31485,162275,19.402249270000000000000
Baja California,2007,1,Mujeres,112553,450574,24.979914510000000000000
Baja California Sur,2007,1,Mujeres,6298,87290,7.2150303590000000000000
Campeche,2007,1,Mujeres,14502,114970,12.613725320000000000000
...,...,...,...,...,...,...
Tamaulipas,2022,1,Mujeres,148943,624871,23.835799710000000000000
Tlaxcala,2022,1,Mujeres,63801,241052,26.46773310000000000000
Veracruz,2022,1,Mujeres,107640,1190733,9.0398099320000000000000
Yucat n,2022,1,Mujeres,82759,478943,17.279509250000000000000
Zacatecas,2022,1,Mujeres,39472,255761,15.43315830000000000000